### PR TITLE
Adds documentation and flowchart for update script refactor

### PR DESCRIPTION
**Pull request by ChrisC**
Adding some additional documentation and a flowchart for the recent [refactor for the `update-bcd` script](https://github.com/openwebdocs/mdn-bcd-collector/pull/801) that were made for @foolip while the changes were being reviewed. @foolip made the suggestion that this additional documentation may be useful to other maintainers and could possibly be added to the repo as well, so offering it here! 

cc @mzgoddard

### CODE REVIEW

**Comment by queengooborg** [comment]
Thanks @ChrisC!  I'll give a proper review later, but I think it would be nice to have the flowchart defined in [Mermaid syntax](https://github.com/mermaid-js/mermaid), which GitHub natively supports, making it easier to modify the flowchart in the future if need be.  Would you be down to make that change?

**Comment by ChrisC** [comment]
> Thanks @ChrisC! I'll give a proper review later, but I think it would be nice to have the flowchart defined in [Mermaid syntax](https://github.com/mermaid-js/mermaid), which GitHub natively supports, making it easier to modify the flowchart in the future if need be. Would you be down to make that change?

Appreciate the mermaid syntax suggestion @queengooborg ! Will look into it and implement the flowchart that way 👍🏽

**Review by queengooborg — CHANGES_REQUESTED** [review]
A few nits!

**Comment by queengooborg** [comment]
Hey @ChrisC, just checking in to see if you plan on returning to this PR!

**Comment by ChrisC** [comment]
> Hey @ChrisC, just checking in to see if you plan on returning to this PR!

I'm hoping to! Wasn't able to make the time for it the last few weeks, but hopefully can return to this in early March! Thanks for checking in 👍🏽

**Comment by queengooborg** [comment]
Awesome!  In that case, would you mind enabling maintainer editing permissions for this PR, if you're able to?  That way, I can push to this PR!

**Comment by ChrisC** [comment]
Ok @queengooborg you should have editing permissions now! Thanks again for offering to help close this out!

**Review by queengooborg — APPROVED** [review]
Thank you!  Let's get this landed!

**Pull request merged**
