### PR TITLE
Remove update-bcd script

### PR DESCRIPTION
**Pull request by Elchi3**
The BCD updating should from now on happen with the `npm run update` script within BCD itself. 
So, we should be removing the script from here.

I think there are two dependencies in the code still, so maybe we want to look into that first. 

Opening this PR to discuss:
- https://github.com/openwebdocs/mdn-bcd-collector/blob/296d82125e1b49da5a62dffad98f9261d5a632f7/scripts/add-new-bcd.ts#L19
- https://github.com/openwebdocs/mdn-bcd-collector/blob/296d82125e1b49da5a62dffad98f9261d5a632f7/scripts/find-missing-reports.ts#L29

### CODE REVIEW

**Comment by Elchi3** [comment]
I guess "add-new-bcd" wasn't ported to BCD yet... Is that correct?

**Comment by queengooborg** [comment]
I'm still -1 on having the update script hosted in the BCD repository, honestly.  The update script requires far too much integration with the collector for me to feel comfortable about moving it into another repository.

**Comment by Elchi3** [comment]
> The update script requires far too much integration with the collector for me to feel comfortable about moving it into another repository.

Other than the two dependencies above, what else needs work?

**Comment by queengooborg** [comment]
It's not about what other scripts need `update-bcd`; it's about what `update-bcd` needs.  It needs more than just the collector results, it also needs overrides data and extensions data from the collector, two files that shouldn't be moved elsewhere.

**Comment by Elchi3** [comment]
As discussed, we aren't removing this script.

**Pull request closed without merging**
