### PR TITLE
Fix the tests for checkVisibility() parameters

### PR DESCRIPTION
**Pull request by foolip**
A simple typo broke these tests. They pass on Safari 17.5 with this change.

### CODE REVIEW

**Comment by foolip** [comment]
@Elchi3 looks like this was closed accidentally, but I can't reopen for some reason...

**Review by Elchi3 — APPROVED** [review]
Thanks Philip! 👍

**Comment by Elchi3** [comment]
Ah, can't merge because we require all commits to be signed. Can you fix that?

**Review by queengooborg — APPROVED** [review]

**Comment by queengooborg** [comment]
Still awaiting commit signing, but LGTM and ready to go otherwise!

**Pull request closed without merging**
